import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import SiteHeader from '@/components/site-header'
import { Providers } from "@/components/provider";

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-pt-[3.5em]">
			<body
				className={`${inter.variable} antialiased`}
			>
				<Providers>
					<div className="flex flex-col min-h-dvh bg-background">
						<SiteHeader />
						<main className="flex-1 font-sans">{children}</main>
					</div>
				</Providers>

			</body>
		</html>
	);
}
